# .NET Core 8 build and test GitHub Actions pipeline

name: .NET Core 8 CI

on:
  push:
  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: windows-latest  

    env:
      buildConfiguration: 'Release'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core 8.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x' 

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the solution
      run: dotnet build --configuration ${{ env.buildConfiguration }} --no-restore

    - name: Run tests
      run: dotnet test --configuration ${{ env.buildConfiguration }} --no-build --verbosity normal

    - name: Publish build artifacts
      if: always()  
      run: |
        mkdir -p artifacts
        dotnet publish --configuration ${{ env.buildConfiguration }} -o artifacts

